name: MobArenaAddOns

main: de.iani.mobarena.MobArenaAddOns

version: 1.0
api-version: 1.13
author: Brokkonaut, Blattfuchs
description: AddOns like FastPvP and Statistics
depend: [MobArena]
softdepend: [CubesideStatistics]
